apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: argo
  labels:
    app: argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo
  template:
    metadata:
      labels:
        app: argo
    spec:
      containers:
      - name: app
        image: IMAGE
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: argo
  labels:
    app: argo
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30030
    name: http
  selector:
    app: argo
